"""
Generate figures/fig_reranker_progression.tex

Source data: figures/data/reranker_progression.csv
Output: figures/fig_reranker_progression.tex

The figure shows the re-ranker stage progression
(Baseline, AlnWeighted, PerAspect, PerCategory, FullFeature) faceted by
evaluation category (NK, LK, PK) with one bar per GO aspect.

Dataset notes:
  Baseline / AlnWeighted / PerAspect / PerCategory: pre-leakage-fix
    bench-v1-K5 (22-feature schema, GOA 220->229).
  FullFeature: leakage-free bench-v1-K5-filtered
    (52-feature schema, GOA 220->230, mean of 3 seeds).
  The earlier stages are directional reference only.
"""

import csv
import pathlib

SCRIPT_DIR = pathlib.Path(__file__).parent
DATA_FILE = SCRIPT_DIR / "data" / "reranker_progression.csv"
OUT_FILE = SCRIPT_DIR / "fig_reranker_progression.tex"

METHODS = ["Baseline", "AlnWeighted", "PerAspect", "PerCategory", "FullFeature"]
CATEGORIES = ["NK", "LK", "PK"]
ASPECTS = ["BPO", "MFO", "CCO"]
COLORS = {
    "BPO": ("proteagreen", "proteagreen!60!black"),
    "MFO": ("linkblue", "linkblue!60!black"),
    "CCO": ("BurntOrange", "BurntOrange!60!black"),
}


def load_data(path: pathlib.Path) -> dict:
    """Return {(method, category, aspect): fmax}."""
    data: dict = {}
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            key = (row["method"], row["category"], row["aspect"])
            data[key] = float(row["fmax"])
    return data


def fmt(v: float) -> str:
    """Format float with 3 decimal places."""
    return f"{v:.3f}"


def coords_bar(data: dict, category: str, aspect: str) -> str:
    parts = [f"({m},{fmt(data[(m, category, aspect)])})" for m in METHODS]
    return " ".join(parts)


def render(data: dict) -> str:
    panels = []
    for i, cat in enumerate(CATEGORIES):
        ymax_extra = ", ymin=0.10, ymax=0.85" if cat == "PK" else ""
        # legend to name is attached to a single panel only; placing it in the
        # group-wide options makes every panel re-emit the same label and
        # triggers "multiply defined label" warnings.
        legend_opt = ", legend to name=reranker-legend" if i == 0 else ""
        lines = [
            f"    % -- {cat} panel",
            f"    \\nextgroupplot[title={{{cat}}}{ymax_extra}, ybar, bar width=2.7pt{legend_opt}]",
        ]
        for j, (asp, (fill, draw)) in enumerate(COLORS.items()):
            lines.append(
                f"      \\addplot+[fill={fill}, draw={draw}]\n"
                f"        coordinates {{{coords_bar(data, cat, asp)}}};"
            )
            if i == 0:
                lines.append(f"      \\addlegendentry{{{asp}}}")
        panels.append("\n".join(lines))

    return (
        "% ============================================================\n"
        "%  Figure: Re-ranker stage progression (Experiments 4 to 6)\n"
        "%  Data source: figures/data/reranker_progression.csv\n"
        "%  Generated by: figures/fig_reranker_progression.py\n"
        "%  Stages: Baseline, AlnWeighted, PerAspect, PerCategory, FullFeature\n"
        "%  NOTE: Baseline/AlnWeighted/PerAspect/PerCategory use the\n"
        "%        pre-leakage-fix bench-v1-K5 dataset (22-feature schema,\n"
        "%        GOA 220->229).\n"
        "%        FullFeature uses leakage-free bench-v1-K5-filtered\n"
        "%        (52-feature schema, GOA 220->230, mean of 3 seeds).\n"
        "%        The earlier stages are directional reference only.\n"
        "% ============================================================\n"
        "\\begin{tikzpicture}\n"
        "  \\begin{groupplot}[\n"
        "    group style={\n"
        "      group size=3 by 1,\n"
        "      horizontal sep=12mm,\n"
        "      ylabels at=edge left,\n"
        "    },\n"
        "    protea plot,\n"
        "    width=6.0cm, height=5.0cm,\n"
        "    enlarge x limits=0.18,\n"
        "    symbolic x coords={Baseline, AlnWeighted, PerAspect, PerCategory, FullFeature},\n"
        "    xtick=data,\n"
        "    xticklabel style={font=\\tiny, rotate=35, anchor=east, yshift=0.5mm},\n"
        "    ymin=0.10, ymax=0.85,\n"
        "    ylabel={$F_{\\max}$},\n"
        "    grid=both,\n"
        "    legend columns=3,\n"
        "    every axis plot/.append style={fill opacity=0.85},\n"
        "  ]\n\n"
        + "\n\n".join(panels)
        + "\n"
        "  \\end{groupplot}\n"
        "\n"
        "  \\node[anchor=north] at ($(group c2r1.south) + (0,-12mm)$)\n"
        "    {\\pgfplotslegendfromname{reranker-legend}};\n"
        "\\end{tikzpicture}\n"
    )


def main() -> None:
    data = load_data(DATA_FILE)
    tex = render(data)
    OUT_FILE.write_text(tex, encoding="utf-8")
    print(f"Written: {OUT_FILE}")


if __name__ == "__main__":
    main()
