"""
Generate figures/fig_protea_vs_emapper.tex

Source data: figures/data/protea_vs_emapper.csv
Output: figures/fig_protea_vs_emapper.tex

Head-to-head Fmax comparison between eggNOG-mapper v2.1.13, PROTEA embedding-only
baseline (pre-leakage-fix), and the PROTEA full-feature re-ranker (leakage-free).
Faceted by evaluation category (NK, LK, PK), x-axis = GO aspect (BPO, MFO, CCO).

Dataset notes:
  eggNOG-mapper 2.1.13 and PROTEA baseline: pre-leakage-fix bench-v1-K5
    (22-feature schema, GOA 220->229).
  PROTEA full-feature: leakage-free bench-v1-K5-filtered
    (52-feature schema, GOA 220->230, mean of 3 seeds).
  Direct cell-by-cell comparison is indicative only.
"""

import csv
import pathlib

SCRIPT_DIR = pathlib.Path(__file__).parent
DATA_FILE = SCRIPT_DIR / "data" / "protea_vs_emapper.csv"
OUT_FILE = SCRIPT_DIR / "fig_protea_vs_emapper.tex"

METHODS_ORDER = ["eggNOG-mapper_2.1.13", "PROTEA_baseline", "PROTEA_full_feature"]
CATEGORIES = ["NK", "LK", "PK"]
ASPECTS = ["BPO", "MFO", "CCO"]

METHOD_STYLE = {
    "eggNOG-mapper_2.1.13": ("black!35", "black!60", "eggNOG-mapper 2.1.13"),
    "PROTEA_baseline": ("linkblue", "linkblue!60!black", "PROTEA baseline"),
    "PROTEA_full_feature": ("proteagreen", "proteagreen!60!black", r"PROTEA full-feature"),
}

# PK panel uses narrower ymax to better show small differences
CAT_YMAX = {"NK": 0.85, "LK": 0.85, "PK": 0.42}


def load_data(path: pathlib.Path) -> dict:
    """Return {(method, category, aspect): fmax}."""
    data: dict = {}
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            key = (row["method"], row["category"], row["aspect"])
            data[key] = float(row["fmax"])
    return data


def fmt(v: float) -> str:
    """Format float with 3 decimal places."""
    return f"{v:.3f}"


def coords_bar(data: dict, method: str, category: str) -> str:
    parts = [f"({asp},{fmt(data[(method, category, asp)])})" for asp in ASPECTS]
    return " ".join(parts)


def render(data: dict) -> str:
    panels = []
    for i, cat in enumerate(CATEGORIES):
        ymax = CAT_YMAX[cat]
        extra = f", ymax={ymax}" if ymax != 0.85 else ""
        # legend to name is attached to a single panel only; placing it in the
        # group-wide options makes every panel re-emit the same label and
        # triggers "multiply defined label" warnings.
        legend_opt = ", legend to name=emapper-legend" if i == 0 else ""
        lines = [
            f"    % -- {cat} panel",
            f"    \\nextgroupplot[title={{{cat}}}{extra}, ybar, bar width=4.5pt{legend_opt}]",
        ]
        for method in METHODS_ORDER:
            fill, draw, legend = METHOD_STYLE[method]
            lines.append(
                f"      \\addplot+[fill={fill}, draw={draw}]\n"
                f"        coordinates {{{coords_bar(data, method, cat)}}};"
            )
            if i == 0:
                lines.append(f"      \\addlegendentry{{{legend}}}")
        panels.append("\n".join(lines))

    return (
        "% ============================================================\n"
        "%  Figure: PROTEA (baseline + full-feature) vs eggNOG-mapper 2.1.13\n"
        "%  Data source: figures/data/protea_vs_emapper.csv\n"
        "%  Generated by: figures/fig_protea_vs_emapper.py\n"
        "%  NOTE: baseline and eggNOG-mapper rows use pre-leakage-fix bench-v1-K5\n"
        "%        (22-feature schema, GOA 220->229).\n"
        "%        The full-feature row uses leakage-free bench-v1-K5-filtered\n"
        "%        (52-feature schema, GOA 220->230, mean of 3 seeds).\n"
        "% ============================================================\n"
        "\\begin{tikzpicture}\n"
        "  \\begin{groupplot}[\n"
        "    group style={\n"
        "      group size=3 by 1,\n"
        "      horizontal sep=10mm,\n"
        "      ylabels at=edge left,\n"
        "    },\n"
        "    protea plot,\n"
        "    width=6.0cm, height=5.0cm,\n"
        "    enlarge x limits=0.25,\n"
        "    symbolic x coords={BPO, MFO, CCO},\n"
        "    xtick=data,\n"
        "    ymin=0, ymax=0.85,\n"
        "    ylabel={$F_{\\max}$},\n"
        "    grid=both,\n"
        "    legend columns=3,\n"
        "    every axis plot/.append style={fill opacity=0.85},\n"
        "    nodes near coords,\n"
        "    nodes near coords style={font=\\tiny, /pgf/number format/fixed,"
        " /pgf/number format/precision=2, /pgf/number format/zerofill},\n"
        "  ]\n\n"
        + "\n\n".join(panels)
        + "\n"
        "  \\end{groupplot}\n"
        "\n"
        "  \\node[anchor=north] at ($(group c2r1.south) + (0,-7mm)$)\n"
        "    {\\pgfplotslegendfromname{emapper-legend}};\n"
        "\\end{tikzpicture}\n"
    )


def main() -> None:
    data = load_data(DATA_FILE)
    tex = render(data)
    OUT_FILE.write_text(tex, encoding="utf-8")
    print(f"Written: {OUT_FILE}")


if __name__ == "__main__":
    main()
