"""
Generate figures/fig_feature_importance.tex

Source data: figures/data/feature_importance_v3.csv
Output: figures/fig_feature_importance.tex

Top-10 LightGBM features by gain (in thousands) for the v3 re-ranker,
aggregated over the three per-aspect models (BPO + MFO + CCO) per category
(NK, LK, PK), seed 42, leakage-free bench-v1-K5-filtered dataset.

Gain values are in thousands. Feature name abbreviations used in chart:
  nb_vote_frac  -> nb-vf
  k_position    -> kpos
  evidence_code -> evcode
  go_term_freq  -> go-freq
  vote_count    -> votes
  anc2vec_n_cos -> anc2vec-n-cos
  ref_ann_dens  -> ref-dens
  emb_pca_q_5   -> emb-pca-5
  emb_pca_q_0   -> emb-pca-0
  anc2vec_n_maxcos -> anc2vec-n-mc
  anc2vec_q_maxcos -> anc2vec-q-mc
  anc2vec_q_count  -> anc2vec-q-count
  anc2vec_q_cos    -> anc2vec-q-cos
  nb_min_dist   -> nb-min-d
  qualifier     -> qual
"""

import csv
import pathlib

SCRIPT_DIR = pathlib.Path(__file__).parent
DATA_FILE = SCRIPT_DIR / "data" / "feature_importance_v3.csv"
OUT_FILE = SCRIPT_DIR / "fig_feature_importance.tex"

ABBREV = {
    "nb_vote_frac": "nb-vf",
    "k_position": "kpos",
    "evidence_code": "evcode",
    "go_term_freq": "go-freq",
    "vote_count": "votes",
    "anc2vec_n_cos": "anc2vec-n-cos",
    "ref_ann_dens": "ref-dens",
    "emb_pca_q_5": "emb-pca-5",
    "emb_pca_q_0": "emb-pca-0",
    "anc2vec_n_maxcos": "anc2vec-n-mc",
    "anc2vec_q_maxcos": "anc2vec-q-mc",
    "anc2vec_q_count": "anc2vec-q-count",
    "anc2vec_q_cos": "anc2vec-q-cos",
    "nb_min_dist": "nb-min-d",
    "qualifier": "qual",
}

LABEL = {
    "nb_vote_frac": r"nb\_vote\_frac",
    "k_position": r"k\_position",
    "evidence_code": r"evidence\_code",
    "go_term_freq": r"go\_term\_freq",
    "vote_count": r"vote\_count",
    "anc2vec_n_cos": r"anc2vec\_n\_cos",
    "ref_ann_dens": r"ref\_ann\_dens.",
    "emb_pca_q_5": r"emb\_pca\_q\_5",
    "emb_pca_q_0": r"emb\_pca\_q\_0",
    "anc2vec_n_maxcos": r"anc2vec\_n\_maxcos",
    "anc2vec_q_maxcos": r"anc2vec\_q\_maxcos",
    "anc2vec_q_count": r"anc2vec\_q\_count",
    "anc2vec_q_cos": r"anc2vec\_q\_cos",
    "nb_min_dist": r"nb\_min\_dist",
    "qualifier": r"qualifier",
}

CAT_COLOR = {
    "NK": ("proteagreen", "proteagreen!60!black"),
    "LK": ("linkblue", "linkblue!60!black"),
    "PK": ("BurntOrange", "BurntOrange!60!black"),
}

CAT_XMAX = {"NK": 180, "LK": 120, "PK": 450}


def load_data(path: pathlib.Path) -> dict:
    """Return {category: [(feature, gain_k), ...]} sorted bottom-to-top."""
    raw: dict = {}
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            cat = row["category"]
            raw.setdefault(cat, []).append((row["feature"], int(row["gain_thousands"])))
    result = {}
    for cat, rows in raw.items():
        rows.sort(key=lambda x: x[1])
        result[cat] = rows
    return result


def render(data: dict) -> str:
    panels = []
    for cat in ["NK", "LK", "PK"]:
        rows = data[cat]
        sym_coords = ",".join(ABBREV[f] for f, _ in rows)
        tick_labels = ",".join(LABEL[f] for f, _ in rows)
        fill, draw = CAT_COLOR[cat]
        xmax = CAT_XMAX[cat]
        coord_str = " ".join(f"({g},{ABBREV[f]})" for f, g in rows)
        panel = (
            f"    % -- {cat} panel\n"
            f"    \\nextgroupplot[\n"
            f"      title={{{cat}}},\n"
            f"      xbar, bar width=3.6pt,\n"
            f"      symbolic y coords={{{sym_coords}}},\n"
            f"      yticklabels={{{tick_labels}}},\n"
            f"      ytick=data,\n"
            f"      xmax={xmax},\n"
            f"    ]\n"
            f"      \\addplot+[fill={fill}, draw={draw}] coordinates {{\n"
            f"        {coord_str}\n"
            f"      }};"
        )
        panels.append(panel)

    return (
        "% ============================================================\n"
        "%  Figure: LightGBM feature importance for v3 re-ranker\n"
        "%  Data source: figures/data/feature_importance_v3.csv\n"
        "%  Generated by: figures/fig_feature_importance.py\n"
        "%  Dataset: bench-v1-K5-filtered (leakage-free), seed 42\n"
        "%  Aggregated over BPO + MFO + CCO per category.\n"
        "%  Gain values are in thousands.\n"
        "% ============================================================\n"
        "\\begin{tikzpicture}\n"
        "  \\begin{groupplot}[\n"
        "    group style={\n"
        "      group size=3 by 1,\n"
        "      horizontal sep=22mm,\n"
        "    },\n"
        "    protea plot,\n"
        "    width=5.5cm, height=6.0cm,\n"
        "    enlarge y limits=0.06,\n"
        "    xmin=0,\n"
        "    xlabel={LightGBM gain (thousands)},\n"
        "    label style={font=\\scriptsize},\n"
        "    yticklabel style={font=\\scriptsize\\ttfamily},\n"
        "    nodes near coords,\n"
        "    nodes near coords style={font=\\tiny, /pgf/number format/fixed,"
        " /pgf/number format/precision=0},\n"
        "    every axis plot/.append style={fill opacity=0.85},\n"
        "    grid=both,\n"
        "  ]\n\n"
        + "\n\n".join(panels)
        + "\n"
        "  \\end{groupplot}\n"
        "\\end{tikzpicture}\n"
    )


def main() -> None:
    data = load_data(DATA_FILE)
    tex = render(data)
    OUT_FILE.write_text(tex, encoding="utf-8")
    print(f"Written: {OUT_FILE}")


if __name__ == "__main__":
    main()
