"""
Generate figures/fig_fmax_vs_k.tex

Source data: figures/data/fmax_vs_k.csv
Output: figures/fig_fmax_vs_k.tex

The figure shows Fmax as a function of the number of KNN neighbours k
for each evaluation category (NK, LK, PK) and GO aspect (BPO, MFO, CCO).
Data matches Table 6.1 in chapters/06_evaluation.tex.

Dataset: pre-leakage-fix bench-v1-K5 (22-feature schema, GOA 220->229).
k values tested: 5, 10, 20, 50. All use aspect_separated_knn=true.
"""

import csv
import pathlib

SCRIPT_DIR = pathlib.Path(__file__).parent
DATA_FILE = SCRIPT_DIR / "data" / "fmax_vs_k.csv"
OUT_FILE = SCRIPT_DIR / "fig_fmax_vs_k.tex"

K_VALUES = [5, 10, 20, 50]
CATEGORIES = ["NK", "LK", "PK"]
CATEGORY_LABELS = {"NK": "NK (No-Knowledge)", "LK": "LK (Limited-Knowledge)", "PK": "PK (Partial-Knowledge)"}
ASPECTS = ["BPO", "MFO", "CCO"]


def load_data(path: pathlib.Path) -> dict:
    """Return {(category, aspect, k): fmax}."""
    data: dict = {}
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            key = (row["category"], row["aspect"], int(row["k"]))
            data[key] = float(row["fmax"])
    return data


def fmt(v: float) -> str:
    """Format float with 3 decimal places, stripping unnecessary trailing zeros."""
    return f"{v:.3f}"


def coords(data: dict, category: str, aspect: str) -> str:
    """Build pgfplots coordinates string for one (category, aspect) series."""
    parts = [f"({k},{fmt(data[(category, aspect, k)])})" for k in K_VALUES]
    return " ".join(parts)


def render(data: dict) -> str:
    panels = []
    for cat in CATEGORIES:
        label = CATEGORY_LABELS[cat]
        lines = [f"    % -- {cat} panel", f"    \\nextgroupplot[title={{{label}}}]"]
        for asp in ASPECTS:
            lines.append(f"      \\addplot coordinates {{{coords(data, cat, asp)}}};")
            lines.append(f"      \\addlegendentry{{{asp}}}")
        panels.append("\n".join(lines))

    return (
        "% ============================================================\n"
        "%  Figure: Fmax as a function of k (Experiment 1)\n"
        "%  Data source: figures/data/fmax_vs_k.csv\n"
        "%  Generated by: figures/fig_fmax_vs_k.py\n"
        "% ============================================================\n"
        "\\begin{tikzpicture}\n"
        "  \\begin{groupplot}[\n"
        "    group style={\n"
        "      group size=3 by 1,\n"
        "      horizontal sep=10mm,\n"
        "      ylabels at=edge left,\n"
        "    },\n"
        "    protea plot,\n"
        "    xmode=log,\n"
        "    log basis x=2,\n"
        "    xtick={5,10,20,50},\n"
        "    xticklabels={5,10,20,50},\n"
        "    xlabel={$k$ (neighbours)},\n"
        "    ylabel={$F_{\\max}$},\n"
        "    ymin=0.15, ymax=0.72,\n"
        "    grid=both,\n"
        "    legend columns=3,\n"
        "    legend to name=fmaxk-legend,\n"
        "  ]\n"
        + "\n\n".join(panels)
        + "\n"
        "  \\end{groupplot}\n"
        "\n"
        "  % Centered legend below the group\n"
        "  \\node[anchor=north] at ($(group c2r1.south) + (0,-7mm)$)\n"
        "    {\\pgfplotslegendfromname{fmaxk-legend}};\n"
        "\\end{tikzpicture}\n"
    )


def main() -> None:
    data = load_data(DATA_FILE)
    tex = render(data)
    OUT_FILE.write_text(tex, encoding="utf-8")
    print(f"Written: {OUT_FILE}")


if __name__ == "__main__":
    main()
